doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'Category\Migrations': '%kernel.project_dir%/src/CustomerAciliaSoftware/Category/Infrastructure/migrations'
