version: '3.5'

services:
  docker-symfony-acilia-web:
    container_name: docker-symfony-acilia-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - 301:80
    volumes:
      - ./public:/appdata/www/public
    networks:
      - docker-symfony-acilia-network
    depends_on:
      - docker-symfony-acilia-be

  docker-symfony-acilia-be:
    container_name: docker-symfony-acilia-be
    build:
      context: ./docker/php
      args:
        UID: $U_ID
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=172.17.0.1 remote_port=9005 # for linux users
#      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9005 # for osx users
    volumes:
      - ./:/appdata/www
      - ./docker/php/xdebug-linux.ini:/usr/local/etc/php/conf.d/xdebug.ini #linux users
#   - ./docker/php/xdebug-mac.ini:/usr/local/etc/php/conf.d/xdebug.ini #osx users
#    - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    networks:
      - docker-symfony-acilia-network
    depends_on:
      - docker-symfony-acilia-db
#    command: ["./wait-for-it.sh", "docker-symfony-acilia-db:40100", "--", "python", "app.py"]

  docker-symfony-acilia-db:
    container_name: docker-symfony-acilia-db
    image: mysql:8.0
    ports:
      - 40100:3306
    environment:
      MYSQL_DATABASE: symfony_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - docker-symfony-acilia-database-data:/var/lib/mysql
    networks:
      - docker-symfony-acilia-network

volumes:
  docker-symfony-acilia-database-data:

networks:
  docker-symfony-acilia-network:
    external: true

